name: MLOps Pipeline

on:
  schedule:
    - cron: '0 0 * * 0'  # Weekly Sunday
  workflow_dispatch:

jobs:
  train-deploy:
    runs-on: [self-hosted, windows]  # Use your self-hosted Windows runner with a matching label

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download data
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          pip install awscli
          aws s3 cp s3://movielens-raw-data/cleaned_data/ratings/ .\data\cloud\ratings --recursive
          aws s3 cp s3://movielens-raw-data/cleaned_data/movies/ .\data\cloud\movies --recursive

      - name: Train model
        run: '"C:\ProgramData\anaconda3\python.exe" train.py'
        shell: cmd

      - name: Validate model
        run: '"C:\ProgramData\anaconda3\python.exe" -c "import joblib; m = joblib.load(\"movie_recommender.pkl\"); assert m.pu.shape[0] > 0"'
        shell: cmd

      - name: Upload model
        uses: actions/upload-artifact@v4.3.0
        with:
          name: model
          path: movie_recommender.pkl

      - name: Deploy model to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp movie_recommender.pkl s3://movielens-models/models/movie_recommender.pkl
